### ISSUE TITLE
gan in 5 minutes runs into an error

### ISSUE THREAD

**Issue by shirishr** [johnolafenwa/TorchFusion#5]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

Trace as under:
Epoch 1 of 50
Traceback (most recent call last):
  File "gan_in_5.py", line 29, in <module>
    learner.train(dataset,gen_optimizer=g_optim,disc_optimizer=d_optim,save_outputs_interval=500,model_dir="./fashion-gan",latent_size=128,num_epochs=50,batch_log=False)
  File "/home/sam/Documents/ComputerVision/TorchFusion/torchfusion/gan/learners/learners.py", line 863, in train
    latent_size=latent_size,**kwargs)
  File "/home/sam/Documents/ComputerVision/TorchFusion/torchfusion/gan/learners/learners.py", line 609, in train
    super().__train_loop__(train_loader, gen_optimizer, disc_optimizer, **kwargs)
  File "/home/sam/Documents/ComputerVision/TorchFusion/torchfusion/gan/learners/learners.py", line 186, in __train_loop__
    self.__disc_train_func__(t)
  File "/home/sam/Documents/ComputerVision/TorchFusion/torchfusion/gan/learners/learners.py", line 665, in __disc_train_func__
    loss.backward()
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by johnolafenwa** [comment]
Hi @shirishr I have rerun the gan in five minutes code and there was no error. 
What version of torchfusion and what version of pytorch were you running on?

**Comment by shirishr** [comment]
My apologies @johnolafenwa,
I forgot that I had switched to pytorch 1.0 rc.
